/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessControlRouteImport } from './routes/access-control'
import { Route as CamerasRouteImport } from './routes/cameras'
import { Route as CybersecurityRouteImport } from './routes/cybersecurity'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VesselsIndexRouteImport } from './routes/vessels.index'
import { Route as VesselsVesselIdRouteImport } from './routes/vessels.$vesselId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessControlRoute = AccessControlRouteImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasRoute = CamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const CybersecurityRoute = CybersecurityRouteImport.update({
  id: '/cybersecurity',
  path: '/cybersecurity',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VesselsIndexRoute = VesselsIndexRouteImport.update({
  id: '/vessels/',
  path: '/vessels/',
  getParentRoute: () => rootRouteImport,
} as any)
const VesselsVesselIdRoute = VesselsVesselIdRouteImport.update({
  id: '/vessels/$vesselId',
  path: '/vessels/$vesselId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/cameras': typeof CamerasRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/reports': typeof ReportsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/vessels/$vesselId': typeof VesselsVesselIdRoute
  '/vessels/': typeof VesselsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/cameras': typeof CamerasRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/reports': typeof ReportsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/vessels/$vesselId': typeof VesselsVesselIdRoute
  '/vessels': typeof VesselsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/cameras': typeof CamerasRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/fleet': typeof FleetRoute
  '/incidents': typeof IncidentsRoute
  '/reports': typeof ReportsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/vessels/$vesselId': typeof VesselsVesselIdRoute
  '/vessels/': typeof VesselsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-control'
    | '/cameras'
    | '/cybersecurity'
    | '/fleet'
    | '/incidents'
    | '/reports'
    | '/sensors'
    | '/settings'
    | '/vessels/$vesselId'
    | '/vessels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-control'
    | '/cameras'
    | '/cybersecurity'
    | '/fleet'
    | '/incidents'
    | '/reports'
    | '/sensors'
    | '/settings'
    | '/vessels/$vesselId'
    | '/vessels'
  id:
    | '__root__'
    | '/'
    | '/access-control'
    | '/cameras'
    | '/cybersecurity'
    | '/fleet'
    | '/incidents'
    | '/reports'
    | '/sensors'
    | '/settings'
    | '/vessels/$vesselId'
    | '/vessels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessControlRoute: typeof AccessControlRoute
  CamerasRoute: typeof CamerasRoute
  CybersecurityRoute: typeof CybersecurityRoute
  FleetRoute: typeof FleetRoute
  IncidentsRoute: typeof IncidentsRoute
  ReportsRoute: typeof ReportsRoute
  SensorsRoute: typeof SensorsRoute
  SettingsRoute: typeof SettingsRoute
  VesselsVesselIdRoute: typeof VesselsVesselIdRoute
  VesselsIndexRoute: typeof VesselsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-control': {
      id: '/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof AccessControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras': {
      id: '/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof CamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurity': {
      id: '/cybersecurity'
      path: '/cybersecurity'
      fullPath: '/cybersecurity'
      preLoaderRoute: typeof CybersecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vessels/': {
      id: '/vessels/'
      path: '/vessels'
      fullPath: '/vessels/'
      preLoaderRoute: typeof VesselsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vessels/$vesselId': {
      id: '/vessels/$vesselId'
      path: '/vessels/$vesselId'
      fullPath: '/vessels/$vesselId'
      preLoaderRoute: typeof VesselsVesselIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessControlRoute: AccessControlRoute,
  CamerasRoute: CamerasRoute,
  CybersecurityRoute: CybersecurityRoute,
  FleetRoute: FleetRoute,
  IncidentsRoute: IncidentsRoute,
  ReportsRoute: ReportsRoute,
  SensorsRoute: SensorsRoute,
  SettingsRoute: SettingsRoute,
  VesselsVesselIdRoute: VesselsVesselIdRoute,
  VesselsIndexRoute: VesselsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
